package com.ruanyun.web.model;
// Generated 2017-9-30 20:15:32 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TArticle generated by hbm2java
 */
@Entity
@Table(name="t_article"
)
public class TArticle  implements java.io.Serializable {


     private Integer articleId;
     private Integer userId;
     private String title;
     private String author;
     private String content;
     private Date createTime;
     private String authorEmail;
     private String keywords;
     private Integer mediaType;
     private Integer articleType;
     private String fileUrl;
     private String linkUrl;
     private String description;

    public TArticle() {
    }

    public TArticle(Integer userId, String title, String author, String content, Date createTime, String authorEmail, String keywords, Integer mediaType, Integer articleType, String fileUrl, String linkUrl, String description) {
       this.userId = userId;
       this.title = title;
       this.author = author;
       this.content = content;
       this.createTime = createTime;
       this.authorEmail = authorEmail;
       this.keywords = keywords;
       this.mediaType = mediaType;
       this.articleType = articleType;
       this.fileUrl = fileUrl;
       this.linkUrl = linkUrl;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="article_id", unique=true, nullable=false)
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="title", length=150)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="author", length=30)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="author_email", length=60)
    public String getAuthorEmail() {
        return this.authorEmail;
    }
    
    public void setAuthorEmail(String authorEmail) {
        this.authorEmail = authorEmail;
    }
    
    @Column(name="keywords")
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    
    @Column(name="media_type")
    public Integer getMediaType() {
        return this.mediaType;
    }
    
    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }
    
    @Column(name="article_type")
    public Integer getArticleType() {
        return this.articleType;
    }
    
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }
    
    @Column(name="file_url")
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }
    
    @Column(name="link_url")
    public String getLinkUrl() {
        return this.linkUrl;
    }
    
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


