package com.ruanyun.web.model;
// Generated 2017-11-20 16:25:20 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TStockInfo generated by hbm2java
 */
@Entity
@Table(name="t_stock_info")
public class TStockInfo  implements java.io.Serializable {


     private String code;
     private String name;
     private BigDecimal hv30;
     private BigDecimal hv60;
     private BigDecimal hv14;
     private BigDecimal hv7;

    public TStockInfo() {
    }

    public TStockInfo(String code, String name, BigDecimal hv30, BigDecimal hv60,BigDecimal hv14,BigDecimal hv7) {
       this.code = code;
       this.name = name;
       this.hv30 = hv30;
       this.hv60 = hv60;
       this.hv14 = hv14;
       this.hv7 = hv7;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=64)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="hv30", nullable=false, precision=10)
    public BigDecimal getHv30() {
        return this.hv30;
    }
    
    public void setHv30(BigDecimal hv30) {
        this.hv30 = hv30;
    }
    
    @Column(name="hv60", nullable=false, precision=10)
    public BigDecimal getHv60() {
        return this.hv60;
    }
    
    public void setHv60(BigDecimal hv60) {
        this.hv60 = hv60;
    }

    @Column(name="hv14", nullable=false, precision=10)
    public BigDecimal getHv14() {
        return this.hv14;
    }

    public void setHv14(BigDecimal hv14) {
        this.hv14 = hv14;
    }


    @Column(name="hv7", nullable=false, precision=10)
    public BigDecimal getHv7() {
        return this.hv7;
    }

    public void setHv7(BigDecimal hv7) {
        this.hv7 = hv7;
    }


}


