package com.ruanyun.web.model;
// Generated 2017-10-21 13:31:25 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TStockPlan generated by hbm2java
 */
@Entity
@Table(name="t_stock_plan")
public class TStockPlan  implements java.io.Serializable {


     private Integer planId;
     private Integer userId;
     private String symbol;
     private String symbolName;
     private String cycle;
     private BigDecimal buyMarketPrice;
     private String buyPriceType;
     private BigDecimal buyLimitPrice;
     private Date buyRecommendDate;
     private BigDecimal buyPrice;
     private Date buyConfirmDate;
     private Date buyEndDate;
     private BigDecimal sellMarketPrice;
     private String sellPriceType;
     private BigDecimal sellLimitPrice;
     private Date sellCreateTime;
     private BigDecimal sellPrice;
     private Date sellConfirmTime;
     private BigDecimal serviceFee;
     private BigDecimal manageFee;
     private String orderStatus;
     private Date createTime;
     private BigDecimal profit;
     private BigDecimal netProfit;

    public TStockPlan() {
    }

    public TStockPlan(Integer userId, String symbol, String symbolName, String cycle, BigDecimal buyMarketPrice, String buyPriceType, BigDecimal buyLimitPrice, Date buyRecommendDate, BigDecimal buyPrice, Date buyConfirmDate, Date buyEndDate, BigDecimal sellMarketPrice, String sellPriceType, BigDecimal sellLimitPrice, Date sellCreateTime, BigDecimal sellPrice, Date sellConfirmTime, BigDecimal serviceFee, BigDecimal manageFee, String orderStatus, Date createTime, BigDecimal profit, BigDecimal netProfit) {
       this.userId = userId;
       this.symbol = symbol;
       this.symbolName = symbolName;
       this.cycle = cycle;
       this.buyMarketPrice = buyMarketPrice;
       this.buyPriceType = buyPriceType;
       this.buyLimitPrice = buyLimitPrice;
       this.buyRecommendDate = buyRecommendDate;
       this.buyPrice = buyPrice;
       this.buyConfirmDate = buyConfirmDate;
       this.buyEndDate = buyEndDate;
       this.sellMarketPrice = sellMarketPrice;
       this.sellPriceType = sellPriceType;
       this.sellLimitPrice = sellLimitPrice;
       this.sellCreateTime = sellCreateTime;
       this.sellPrice = sellPrice;
       this.sellConfirmTime = sellConfirmTime;
       this.serviceFee = serviceFee;
       this.manageFee = manageFee;
       this.orderStatus = orderStatus;
       this.createTime = createTime;
       this.profit = profit;
       this.netProfit = netProfit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="plan_id", unique=true, nullable=false)
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }
    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="symbol", length=32)
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    
    @Column(name="symbol_name", length=32)
    public String getSymbolName() {
        return this.symbolName;
    }
    
    public void setSymbolName(String symbolName) {
        this.symbolName = symbolName;
    }
    
    @Column(name="cycle", length=32)
    public String getCycle() {
        return this.cycle;
    }
    
    public void setCycle(String cycle) {
        this.cycle = cycle;
    }
    
    @Column(name="buy_market_price", precision=18)
    public BigDecimal getBuyMarketPrice() {
        return this.buyMarketPrice;
    }
    
    public void setBuyMarketPrice(BigDecimal buyMarketPrice) {
        this.buyMarketPrice = buyMarketPrice;
    }
    
    @Column(name="buy_price_type", length=32)
    public String getBuyPriceType() {
        return this.buyPriceType;
    }
    
    public void setBuyPriceType(String buyPriceType) {
        this.buyPriceType = buyPriceType;
    }
    
    @Column(name="buy_limit_price", precision=18)
    public BigDecimal getBuyLimitPrice() {
        return this.buyLimitPrice;
    }
    
    public void setBuyLimitPrice(BigDecimal buyLimitPrice) {
        this.buyLimitPrice = buyLimitPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buy_recommend_date", length=19)
    public Date getBuyRecommendDate() {
        return this.buyRecommendDate;
    }
    
    public void setBuyRecommendDate(Date buyRecommendDate) {
        this.buyRecommendDate = buyRecommendDate;
    }
    
    @Column(name="buy_price", precision=18)
    public BigDecimal getBuyPrice() {
        return this.buyPrice;
    }
    
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buy_confirm_date", length=19)
    public Date getBuyConfirmDate() {
        return this.buyConfirmDate;
    }
    
    public void setBuyConfirmDate(Date buyConfirmDate) {
        this.buyConfirmDate = buyConfirmDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buy_end_date", length=19)
    public Date getBuyEndDate() {
        return this.buyEndDate;
    }
    
    public void setBuyEndDate(Date buyEndDate) {
        this.buyEndDate = buyEndDate;
    }
    
    @Column(name="sell_market_price", precision=18)
    public BigDecimal getSellMarketPrice() {
        return this.sellMarketPrice;
    }
    
    public void setSellMarketPrice(BigDecimal sellMarketPrice) {
        this.sellMarketPrice = sellMarketPrice;
    }
    
    @Column(name="sell_price_type", length=32)
    public String getSellPriceType() {
        return this.sellPriceType;
    }
    
    public void setSellPriceType(String sellPriceType) {
        this.sellPriceType = sellPriceType;
    }
    
    @Column(name="sell_limit_price", precision=18)
    public BigDecimal getSellLimitPrice() {
        return this.sellLimitPrice;
    }
    
    public void setSellLimitPrice(BigDecimal sellLimitPrice) {
        this.sellLimitPrice = sellLimitPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sell_create_time", length=19)
    public Date getSellCreateTime() {
        return this.sellCreateTime;
    }
    
    public void setSellCreateTime(Date sellCreateTime) {
        this.sellCreateTime = sellCreateTime;
    }
    
    @Column(name="sell_price", precision=18)
    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sell_confirm_time", length=19)
    public Date getSellConfirmTime() {
        return this.sellConfirmTime;
    }
    
    public void setSellConfirmTime(Date sellConfirmTime) {
        this.sellConfirmTime = sellConfirmTime;
    }
    
    @Column(name="service_fee", precision=18)
    public BigDecimal getServiceFee() {
        return this.serviceFee;
    }
    
    public void setServiceFee(BigDecimal serviceFee) {
        this.serviceFee = serviceFee;
    }
    
    @Column(name="manage_fee", precision=18)
    public BigDecimal getManageFee() {
        return this.manageFee;
    }
    
    public void setManageFee(BigDecimal manageFee) {
        this.manageFee = manageFee;
    }
    
    @Column(name="order_status", length=32)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="profit", precision=18)
    public BigDecimal getProfit() {
        return this.profit;
    }
    
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }
    
    @Column(name="net_profit", precision=18)
    public BigDecimal getNetProfit() {
        return this.netProfit;
    }
    
    public void setNetProfit(BigDecimal netProfit) {
        this.netProfit = netProfit;
    }




}


