package com.ruanyun.web.model;
// Generated 2017-10-7 9:34:29 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUserInfo generated by hbm2java
 */
@Entity
@Table(name="t_user_info"
)
public class TUserInfo  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String idNumber;
     private String idCardFrontView;
     private String idCardBackView;
     private String bankId;
     private String bankCardNumber;
     private String depositBank;
     private String backCardPhoto;
     private Integer status;

    public TUserInfo() {
    }

	
    public TUserInfo(Integer userId) {
        this.userId = userId;
    }
    public TUserInfo(Integer userId, String userName, String idNumber, String idCardFrontView,
                     String idCardBackView, String bankId, String bankCardNumber,
                     String backCardPhoto,Integer status,String depositBank) {
       this.userId = userId;
       this.userName = userName;
       this.idNumber = idNumber;
       this.idCardFrontView = idCardFrontView;
       this.idCardBackView = idCardBackView;
       this.bankId = bankId;
       this.bankCardNumber = bankCardNumber;
       this.depositBank = depositBank;
       this.backCardPhoto = backCardPhoto;
       this.status=status;
    }
   
     @Id 
    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="user_name", length=32)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="id_number", length=32)
    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }
    
    @Column(name="id_card_front_view", length=65535)
    public String getIdCardFrontView() {
        return this.idCardFrontView;
    }
    
    public void setIdCardFrontView(String idCardFrontView) {
        this.idCardFrontView = idCardFrontView;
    }
    
    @Column(name="id_card_back_view", length=65535)
    public String getIdCardBackView() {
        return this.idCardBackView;
    }
    
    public void setIdCardBackView(String idCardBackView) {
        this.idCardBackView = idCardBackView;
    }
    
    @Column(name="bank_id", length=32)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    
    @Column(name="bank_card_number", length=32)
    public String getBankCardNumber() {
        return this.bankCardNumber;
    }
    
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber;
    }

    @Column(name="deposit_bank")
    public String getDepositBank() {
        return depositBank;
    }

    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank;
    }

    @Column(name="back_card_photo", length=65535)
    public String getBackCardPhoto() {
        return this.backCardPhoto;
    }
    
    public void setBackCardPhoto(String backCardPhoto) {
        this.backCardPhoto = backCardPhoto;
    }

    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


}


