package com.ruanyun.web.model;
// Generated 2017-10-1 16:29:54 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserAccount generated by hbm2java
 */
@Entity
@Table(name="t_user_account"
)
public class TUserAccount  implements java.io.Serializable {


     private int userId;
     private BigDecimal money;
     private BigDecimal freezingMoney;
     private BigDecimal integral;
     private Date createTime;
     private Date updateTime;

    public TUserAccount() {
    }

	
    public TUserAccount(int userId) {
        this.userId = userId;
    }
    public TUserAccount(int userId, BigDecimal money, BigDecimal freezingMoney, BigDecimal integral, Date createTime, Date updateTime) {
       this.userId = userId;
       this.money = money;
       this.freezingMoney = freezingMoney;
       this.integral = integral;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
     @Id 
    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="money", precision=18)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    
    @Column(name="freezing_money", precision=18)
    public BigDecimal getFreezingMoney() {
        return this.freezingMoney;
    }
    
    public void setFreezingMoney(BigDecimal freezingMoney) {
        this.freezingMoney = freezingMoney;
    }
    
    @Column(name="integral", precision=18)
    public BigDecimal getIntegral() {
        return this.integral;
    }
    
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


