package com.ruanyun.web.model;
// Generated 2017-10-20 18:15:44 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserAccountOperation generated by hbm2java
 */
@Entity
@Table(name="t_user_account_operation")
public class TUserAccountOperation  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private BigDecimal money;
     private String status;
     private Integer applyUserId;
     private Date createDateTime;
     private Integer handleUserId;
     private Date handleDateTime;

    public TUserAccountOperation() {
    }

    public TUserAccountOperation(Integer userId, BigDecimal money, String status, Integer applyUserId, Date createDateTime, Integer handleUserId, Date handleDateTime) {
       this.userId = userId;
       this.money = money;
       this.status = status;
       this.applyUserId = applyUserId;
       this.createDateTime = createDateTime;
       this.handleUserId = handleUserId;
       this.handleDateTime = handleDateTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="money", precision=18)
    public BigDecimal getMoney() {
        return this.money;
    }
    
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
    
    @Column(name="status", length=32)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="apply_user_id")
    public Integer getApplyUserId() {
        return this.applyUserId;
    }
    
    public void setApplyUserId(Integer applyUserId) {
        this.applyUserId = applyUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date_time", length=19)
    public Date getCreateDateTime() {
        return this.createDateTime;
    }
    
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }
    
    @Column(name="handle_user_id")
    public Integer getHandleUserId() {
        return this.handleUserId;
    }
    
    public void setHandleUserId(Integer handleUserId) {
        this.handleUserId = handleUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="handle_date_time", length=19)
    public Date getHandleDateTime() {
        return this.handleDateTime;
    }
    
    public void setHandleDateTime(Date handleDateTime) {
        this.handleDateTime = handleDateTime;
    }




}


