package com.ruanyun.web.model;
// Generated 2017-10-5 1:14:21 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUserBank generated by hbm2java
 */
@Entity
@Table(name="t_user_bank"
)
public class TUserBank  implements java.io.Serializable {


     private int userId;
     private String realName;
     private String idNumber;
     private String bankNumber;
     private String bankName;

    public TUserBank() {
    }

	
    public TUserBank(int userId) {
        this.userId = userId;
    }
    public TUserBank(int userId, String realName, String idNumber, String bankNumber, String bankName) {
       this.userId = userId;
       this.realName = realName;
       this.idNumber = idNumber;
       this.bankNumber = bankNumber;
       this.bankName = bankName;
    }
   
     @Id 
    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="real_name", length=32)
    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }
    
    @Column(name="id_number", length=32)
    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }
    
    @Column(name="bank_number", length=32)
    public String getBankNumber() {
        return this.bankNumber;
    }
    
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber;
    }
    
    @Column(name="bank_name", length=32)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }




}


