package com.ruanyun.web.model.sys;
// Generated 2016-9-20 18:31:06 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAreas generated by hbm2java
 */
@Entity
@Table(name="t_areas"
)
public class TAreas  implements java.io.Serializable {


     private Integer id;
     private String areaid;
     private String area;
     private String cityCode;
     private String cityName;
     private Integer level;
     private Integer isOpen;
     

    public TAreas() {
    }

	
    public TAreas(String areaid, String area, String cityCode) {
        this.areaid = areaid;
        this.area = area;
        this.cityCode = cityCode;
    }
   
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="areaid", nullable=false, length=20)
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    
    @Column(name="area", nullable=false, length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    @Column(name="city_code", nullable=false, length=20)
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }
    
    


    @Column(name="city_name")
	public String getCityName() {
		return cityName;
	}


	public void setCityName(String cityName) {
		this.cityName = cityName;
	}


	@Column(name="level")
	public Integer getLevel() {
		return level;
	}


	public void setLevel(Integer level) {
		this.level = level;
	}


	@Column(name="is_open")
	public Integer getIsOpen() {
		return isOpen;
	}


	public void setIsOpen(Integer isOpen) {
		this.isOpen = isOpen;
	}




}


