package com.ruanyun.web.model.sys;
// Generated 2016-4-8 23:21:24 by Hibernate Tools 3.2.2.GA


import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TAttachInfo generated by hbm2java
 */
@Entity
@Table(name="t_attach_info"
)
public class TAttachInfo  implements java.io.Serializable {


     private Integer attachId;
     private String filePath;
     private String fileName;
     private String fileSize;
     private String userNum;
     private Date createTime;
     private String attachType;  //直接存表名
     private String glNum; //关联num
     
    public TAttachInfo() {
    }
    

	public TAttachInfo(Integer attachId) {
		this.attachId = attachId;
	}

	public TAttachInfo(String filePath, String fileName, String fileSize, String userNum, Date createTime,
			String attachType, String glNum) {
		this.filePath = filePath;
		this.fileName = fileName;
		this.fileSize = fileSize;
		this.userNum = userNum;
		this.createTime = createTime;
		this.attachType = attachType;
		this.glNum = glNum;
	}


	public TAttachInfo(Date createTime) {
        this.createTime = createTime;
    }
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="attach_id", unique=true, nullable=false)
    public Integer getAttachId() {
        return this.attachId;
    }
    
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }
    
    @Column(name="file_path", length=100)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    
    @Column(name="file_name", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="file_size", length=100)
    public String getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }
    
    
    @Column(name="user_num", length=50)
    public String getUserNum() {
		return userNum;
	}

	public void setUserNum(String userNum) {
		this.userNum = userNum;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
     
    @Column(name="gl_num", length=50)
	public String getGlNum() {
		return glNum;
	}

	public void setGlNum(String glNum) {
		this.glNum = glNum;
	}


	@Column(name="attach_type")
	public String getAttachType() {
		return attachType;
	}


	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}
	
	

}


