package com.ruanyun.web.model.sys;
// Generated 2016-9-20 18:31:06 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCity generated by hbm2java
 */
@Entity
@Table(name="t_city"
)
public class TCity  implements java.io.Serializable {


     private int cityId;
     private String cityCode;
     private String cityName;
     private String provinceCode;
     private Integer status;

    public TCity() {
    }

	
    public TCity(int cityId) {
        this.cityId = cityId;
    }
    public TCity(int cityId, String cityCode, String cityName, String provinceCode, Integer status) {
       this.cityId = cityId;
       this.cityCode = cityCode;
       this.cityName = cityName;
       this.provinceCode = provinceCode;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="city_id", unique=true, nullable=false)
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    
    @Column(name="city_code", length=10)
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }
    
    @Column(name="city_name", length=50)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    
    @Column(name="province_code", length=11)
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


