package com.ruanyun.web.model.sys;
// Generated 2013-11-22 9:55:13 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TOperationLog generated by hbm2java
 */
@Entity
@Table(name="t_operation_log"
)
public class TOperationLog  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer operationId;
     private String operationName;
     private String operationContent;
     private Date createdate;
     private Integer operationUser;
     private String operationUserName;
     private String operationType;
     /**
      * 结束时间
      */
     private Date endDate;

    public TOperationLog() {
    }

    public TOperationLog(String operationName, String operationContent, Date createdate, Integer operationUser, String operationUserName, String operationType) {
       this.operationName = operationName;
       this.operationContent = operationContent;
       this.createdate = createdate;
       this.operationUser = operationUser;
       this.operationUserName = operationUserName;
       this.operationType = operationType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="operation_id", unique=true, nullable=false)
    public Integer getOperationId() {
        return this.operationId;
    }
    
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }
    
    @Column(name="operation_name", length=100)
    public String getOperationName() {
        return this.operationName;
    }
    
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }
    
    @Column(name="operation_content", length=2000)
    public String getOperationContent() {
        return this.operationContent;
    }
    
    public void setOperationContent(String operationContent) {
        this.operationContent = operationContent;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate", length=19)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    
    @Column(name="operation_user")
    public Integer getOperationUser() {
        return this.operationUser;
    }
    
    public void setOperationUser(Integer operationUser) {
        this.operationUser = operationUser;
    }
    
    @Column(name="operation_user_name", length=100)
    public String getOperationUserName() {
        return this.operationUserName;
    }
    
    public void setOperationUserName(String operationUserName) {
        this.operationUserName = operationUserName;
    }
    
    @Column(name="operation_type", length=100)
    public String getOperationType() {
        return this.operationType;
    }
    
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }
@Transient
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}




}


