package com.ruanyun.web.model.sys;
// Generated 2013-11-22 9:55:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRoleAuthority generated by hbm2java
 */
@Entity
@Table(name="t_role_authority"
)
public class TRoleAuthority  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer roleAuthorityId;
     private String authCode;
     private Integer roleId;

    public TRoleAuthority() {
    }

    public TRoleAuthority(String authCode, Integer roleId) {
       this.authCode = authCode;
       this.roleId = roleId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="role_authority_id", unique=true, nullable=false)
    public Integer getRoleAuthorityId() {
        return this.roleAuthorityId;
    }
    
    public void setRoleAuthorityId(Integer roleAuthorityId) {
        this.roleAuthorityId = roleAuthorityId;
    }
    
    @Column(name="auth_code", length=100)
    public String getAuthCode() {
        return this.authCode;
    }
    
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }
    
    @Column(name="role_id")
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }




}


