package com.ruanyun.web.model.sys;
// Generated 2013-11-22 9:55:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TRole generated by hbm2java
 */
@Entity
@Table(name="t_role"
)
public class TRole  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer roleId;
     private String roleName;
     private Integer orderby;

    public TRole() {
    }

    public TRole(String roleName, Integer orderby) {
       this.roleName = roleName;
       this.orderby = orderby;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="role_id", unique=true, nullable=false)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="role_name", length=500)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    @Column(name="orderby")
    public Integer getOrderby() {
        return this.orderby;
    }
    
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }




}


