package com.ruanyun.web.model.sys;
// Generated 2016-4-15 18:21:22 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTown generated by hbm2java
 */
@Entity
@Table(name="t_town"
)
public class TTown  implements java.io.Serializable {


     private int townId;
     private String townCode;
     private String townName;
     private String areasCode;
     private Integer status;

    public TTown() {
    }

	
    public TTown(int townId) {
        this.townId = townId;
    }
    public TTown(int townId, String townCode, String townName, String areasCode, Integer status) {
       this.townId = townId;
       this.townCode = townCode;
       this.townName = townName;
       this.areasCode = areasCode;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="town_id", unique=true, nullable=false)
    public int getTownId() {
        return this.townId;
    }
    
    public void setTownId(int townId) {
        this.townId = townId;
    }
    
    @Column(name="town_code", length=10)
    public String getTownCode() {
        return this.townCode;
    }
    
    public void setTownCode(String townCode) {
        this.townCode = townCode;
    }
    
    @Column(name="town_name", length=50)
    public String getTownName() {
        return this.townName;
    }
    
    public void setTownName(String townName) {
        this.townName = townName;
    }
    
    @Column(name="areas_code", length=11)
    public String getAreasCode() {
        return this.areasCode;
    }
    
    public void setAreasCode(String areasCode) {
        this.areasCode = areasCode;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


