package com.ruanyun.web.model.mall;
// Generated 2017-8-4 13:45:33 by Hibernate Tools 3.2.2.GA


import com.ruanyun.web.model.sys.TUser;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TCommentInfo generated by hbm2java
 */
@Entity
@Table(name="t_comment_info"
)
public class TCommentInfo  implements java.io.Serializable {


     private Integer commentId;
     private String commentNum;
     private String shopNum;
     private String mealName;
     private String mealNum;
     private String userNum;
     private String orderNum;
     private Double score;
     private String content;
     private Date updateTime;
     private Date createTime;
     private Integer status;
     private String flag1;
     private String flag2;
     private String flag3;

     private TUser user;
     private Date startTime;

    public TCommentInfo() {
    }

    public TCommentInfo(String commentNum, String shopNum, String mealName, String mealNum, String userNum, String orderNum, Double score, String content, Date createTime, Integer status, String flag1, String flag2, String flag3) {
        this.commentNum = commentNum;
        this.shopNum = shopNum;
        this.mealName = mealName;
        this.mealNum = mealNum;
        this.userNum = userNum;
        this.orderNum = orderNum;
        this.score = score;
        this.content = content;
        this.createTime = createTime;
        this.status = status;
        this.flag1 = flag1;
        this.flag2 = flag2;
        this.flag3 = flag3;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="comment_id", unique=true, nullable=false)
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
    
    @Column(name="comment_num", length=100)
    public String getCommentNum() {
        return this.commentNum;
    }
    
    public void setCommentNum(String commentNum) {
        this.commentNum = commentNum;
    }
    
    @Column(name="meal_name", length=100)
    public String getMealName() {
        return this.mealName;
    }
    
    public void setMealName(String mealName) {
        this.mealName = mealName;
    }
    
    @Column(name="meal_num", length=100)
    public String getMealNum() {
        return this.mealNum;
    }
    
    public void setMealNum(String mealNum) {
        this.mealNum = mealNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="score", precision=10)
    public Double getScore() {
        return this.score;
    }
    
    public void setScore(Double score) {
        this.score = score;
    }
    
    @Column(name="content", length=1000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    @Transient
    public TUser getUser() {
        return user;
    }

    public void setUser(TUser user) {
        this.user = user;
    }

    @Column(name = "order_num", length = 100)
    public String getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    @Column(name = "shop_num", length = 100)
    public String getShopNum() {
        return shopNum;
    }

    public void setShopNum(String shopNum) {
        this.shopNum = shopNum;
    }

    @Transient
    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}


