package com.ruanyun.web.model.mall;
// Generated 2017-1-9 14:00:20 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrderTrain generated by hbm2java
 */
@Entity
@Table(name="t_order_train"
)
public class TOrderTrain  implements java.io.Serializable {


     private Integer orderTrainId;
     private String outTrainOrder;
     private String orderNum;
     private Date createTime;
     private BigDecimal totalPrice;
     private String flag1;
     private String flag2;
     private String flag3;

    public TOrderTrain() {
    }

	
    public TOrderTrain(Date createTime) {
        this.createTime = createTime;
    }
    public TOrderTrain(String outTrainOrder, String orderNum, Date createTime, String flag1, String flag2, String flag3) {
       this.outTrainOrder = outTrainOrder;
       this.orderNum = orderNum;
       this.createTime = createTime;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="order_train_id", unique=true, nullable=false)
    public Integer getOrderTrainId() {
        return this.orderTrainId;
    }
    
    public void setOrderTrainId(Integer orderTrainId) {
        this.orderTrainId = orderTrainId;
    }
    
    @Column(name="out_train_order", length=100)
    public String getOutTrainOrder() {
        return this.outTrainOrder;
    }
    
    public void setOutTrainOrder(String outTrainOrder) {
        this.outTrainOrder = outTrainOrder;
    }
    
    @Column(name="order_num", length=500)
    public String getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="flag1", length=10)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=10)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=10)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }


	

    @Column(name="total_price", precision=10)
    public BigDecimal getTotalPrice() {
		return totalPrice;
	}


	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}


}


