package com.ruanyun.web.model.mall;
// Generated 2016-10-14 18:43:18 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ruanyun.web.model.sys.TUser;

/**
 * TPayInfo generated by hbm2java
 */
@Entity
@Table(name="t_pay_info"
    
)
public class TPayInfo  implements java.io.Serializable {


     private Integer payInfoId;
     private Integer payType;
     private String partner;
     private String publicKey;
     private String privateKeyAndroid;
     private String privateKeyIos;
     private String commonKey;
     private String userNum;
     private Date createTime;
     
     private TUser user;

    public TPayInfo() {
    }

	
    public TPayInfo(Date createTime) {
        this.createTime = createTime;
    }
    public TPayInfo(Integer payType, String partner, String publicKey, String privateKeyAndroid, String privateKeyIos, String commonKey,  String userNum, Date createTime) {
       this.payType = payType;
       this.partner = partner;
       this.publicKey = publicKey;
       this.privateKeyAndroid = privateKeyAndroid;
       this.privateKeyIos = privateKeyIos;
       this.commonKey = commonKey;
       this.userNum = userNum;
       this.createTime = createTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pay_info_id", unique=true, nullable=false)
    public Integer getPayInfoId() {
        return this.payInfoId;
    }
    
    public void setPayInfoId(Integer payInfoId) {
        this.payInfoId = payInfoId;
    }
    
    @Column(name="pay_type")
    public Integer getPayType() {
        return this.payType;
    }
    
    public void setPayType(Integer payType) {
        this.payType = payType;
    }
    
    @Column(name="partner", length=100)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }
    
    @Column(name="public_key", length=1000)
    public String getPublicKey() {
        return this.publicKey;
    }
    
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }
    
    @Column(name="private_key_android", length=1000)
    public String getPrivateKeyAndroid() {
        return this.privateKeyAndroid;
    }
    
    public void setPrivateKeyAndroid(String privateKeyAndroid) {
        this.privateKeyAndroid = privateKeyAndroid;
    }
    
    @Column(name="private_key_ios", length=1000)
    public String getPrivateKeyIos() {
        return this.privateKeyIos;
    }
    
    public void setPrivateKeyIos(String privateKeyIos) {
        this.privateKeyIos = privateKeyIos;
    }
    
    @Column(name="common_key", length=1000)
    public String getCommonKey() {
        return this.commonKey;
    }
    
    public void setCommonKey(String commonKey) {
        this.commonKey = commonKey;
    }
    
     
    
    @Column(name="user_num", length=50)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Transient
	public TUser getUser() {
		return user;
	}


	public void setUser(TUser user) {
		this.user = user;
	}
    
    
    




}


