package com.ruanyun.web.model.mall;
// Generated 2017-8-21 10:59:22 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TShopVedio generated by hbm2java
 */
@Entity
@Table(name="t_shop_vedio")
public class TShopVedio  implements java.io.Serializable {


     private Integer videoId;
     private String videoNum;
     private String videoTitle;
     private String videoUrl;
     private Date createTime;
     private String shopNum;
     private String mainPhotoUrl;
     private Integer videoLength;
     private String flag1;
     private String flag2;
     private String flag3;

    public TShopVedio() {
    }

	
    public TShopVedio(Date createTime) {
        this.createTime = createTime;
    }
    public TShopVedio(String videoNum, String videoUrl, Date createTime, String shopNum, String mainPhotoUrl, Integer videoLength, String flag1, String flag2, String flag3) {
       this.videoNum = videoNum;
       this.videoUrl = videoUrl;
       this.createTime = createTime;
       this.shopNum = shopNum;
       this.mainPhotoUrl = mainPhotoUrl;
       this.videoLength = videoLength;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="video_id", unique=true, nullable=false)
    public Integer getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
    
    @Column(name="video_num")
    public String getVideoNum() {
        return this.videoNum;
    }
    
    public void setVideoNum(String videoNum) {
        this.videoNum = videoNum;
    }
    
    @Column(name="video_title")
    public String getVideoTitle() {
		return videoTitle;
	}


	public void setVideoTitle(String videoTitle) {
		this.videoTitle = videoTitle;
	}


	@Column(name="video_url", length=200)
    public String getVideoUrl() {
        return this.videoUrl;
    }
    
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="shop_num", length=100)
    public String getShopNum() {
        return this.shopNum;
    }
    
    public void setShopNum(String shopNum) {
        this.shopNum = shopNum;
    }
    
    @Column(name="main_photo_url")
    public String getMainPhotoUrl() {
        return this.mainPhotoUrl;
    }
    
    public void setMainPhotoUrl(String mainPhotoUrl) {
        this.mainPhotoUrl = mainPhotoUrl;
    }
    
    @Column(name="video_length")
    public Integer getVideoLength() {
        return this.videoLength;
    }
    
    public void setVideoLength(Integer videoLength) {
        this.videoLength = videoLength;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }




}


