package com.ruanyun.web.model.mall;
// Generated 2016-9-22 12:00:23 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ruanyun.web.model.sys.TUser;

/**
 * TUserCenter generated by hbm2java
 */
@Entity
@Table(name="t_user_center" 
)
public class TUserCenter  implements java.io.Serializable {


     private Integer userCenterId;
     private String userCenterNum;
     private String userNum;
     private BigDecimal accountBalance;
     private Double scoreBalance;
     private String payPassword;
     private String flag1;
     private String flag2;
     private String flag3;
     private Integer bindStatus;


	public TUserCenter() {
    }
    public TUserCenter(String userNum, BigDecimal accountBalance, Double scoreBalance) {
        this.userNum = userNum;
        this.accountBalance = accountBalance;
        this.scoreBalance = scoreBalance;
     }
    public TUserCenter(String userCenterNum, String userNum, BigDecimal accountBalance, Double scoreBalance, String flag1, String flag2, String flag3) {
       this.userCenterNum = userCenterNum;
       this.userNum = userNum;
       this.accountBalance = accountBalance;
       this.scoreBalance = scoreBalance;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_center_id", unique=true, nullable=false)
    public Integer getUserCenterId() {
        return this.userCenterId;
    }
    
    public void setUserCenterId(Integer userCenterId) {
        this.userCenterId = userCenterId;
    }
    
    @Column(name="user_center_num", length=100)
    public String getUserCenterNum() {
        return this.userCenterNum;
    }
    
    public void setUserCenterNum(String userCenterNum) {
        this.userCenterNum = userCenterNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="account_balance", precision=10)
    public BigDecimal getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(BigDecimal accountBalance) {
        this.accountBalance = accountBalance;
    }
    
    @Column(name="score_balance")
    public Double getScoreBalance() {
        return this.scoreBalance;
    }
    
    public void setScoreBalance(Double scoreBalance) {
        this.scoreBalance = scoreBalance;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Transient
	public String getPayPassword() {
		return payPassword;
	}
	public void setPayPassword(String payPassword) {
		this.payPassword = payPassword;
	}
	
	@Transient
    public Integer getBindStatus() {
		return bindStatus;
	}
	public void setBindStatus(Integer bindStatus) {
		this.bindStatus = bindStatus;
	}


}


