package com.ruanyun.web.model.daowei;
// Generated 2017-8-4 10:33:48 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTypeInfo generated by hbm2java
 */
@Entity
@Table(name="t_type_info"
)
public class TTypeInfo  implements java.io.Serializable {


     private Integer typeId;
     private String typeNum;
     private String typeInfoName;
     private String imgUrl;
     private Integer sortNum;
     private String userNum;
     private Date createTime;
     private Integer typeNumber;
     private Integer isVip;
     private Integer memberLevel;
     private String flag1;
     private String flag2;
     private String flag3;

    public TTypeInfo() {
    }

	
    public TTypeInfo(Date createTime) {
        this.createTime = createTime;
    }

    public TTypeInfo(String typeNum, String typeInfoName, String imgUrl, Integer sortNum, String userNum, Date createTime, Integer typeNumber, String flag1, String flag2, String flag3) {
        this.typeNum = typeNum;
        this.typeInfoName = typeInfoName;
        this.imgUrl = imgUrl;
        this.sortNum = sortNum;
        this.userNum = userNum;
        this.createTime = createTime;
        this.typeNumber = typeNumber;
        this.flag1 = flag1;
        this.flag2 = flag2;
        this.flag3 = flag3;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="type_id", unique=true, nullable=false)
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    
    @Column(name="type_num", length=100)
    public String getTypeNum() {
        return this.typeNum;
    }
    
    public void setTypeNum(String typeNum) {
        this.typeNum = typeNum;
    }
    
    @Column(name="type_info_name", length=100)
    public String getTypeInfoName() {
        return this.typeInfoName;
    }
    
    public void setTypeInfoName(String typeInfoName) {
        this.typeInfoName = typeInfoName;
    }
    
    @Column(name="img_url", length=100)
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    
    @Column(name="sort_num")
    public Integer getSortNum() {
        return this.sortNum;
    }
    
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }

    @Column(name = "type_number", length = 100)
    public Integer getTypeNumber() {
        return typeNumber;
    }
    public void setTypeNumber(Integer typeNumber) {
        this.typeNumber = typeNumber;
    }

    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
        
    @Column(name = "is_vip")
    public Integer getIsVip() {
		return isVip;
	}


	public void setIsVip(Integer isVip) {
		this.isVip = isVip;
	}


	@Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    @Column(name="member_level")
	public Integer getMemberLevel() {
		return memberLevel;
	}


	public void setMemberLevel(Integer memberLevel) {
		this.memberLevel = memberLevel;
	}
    
    




}


